use super::super::*;

/// Lean's comment lexer, reduced to what the header can break: `--` line
/// comments, string literals, and nesting `/- … -/` block comments. Returns
/// `Err(line)` at an unbalanced `-/`, or at EOF inside a block comment.
fn check_block_comments(lean: &str) -> Result<(), usize> {
    let b = lean.as_bytes();
    let (mut i, mut depth, mut line) = (0, 0usize, 1usize);
    while i < b.len() {
        let two = &b[i..(i + 2).min(b.len())];
        if b[i] == b'\n' {
            line += 1;
            i += 1;
        } else if depth == 0 && two == b"--" {
            while i < b.len() && b[i] != b'\n' {
                i += 1;
            }
        } else if depth == 0 && b[i] == b'"' {
            i += 1;
            while i < b.len() && b[i] != b'"' {
                i += if b[i] == b'\\' { 2 } else { 1 };
            }
            i += 1;
        } else if two == b"/-" {
            depth += 1;
            i += 2;
        } else if two == b"-/" {
            if depth == 0 {
                return Err(line);
            }
            depth -= 1;
            i += 2;
        } else {
            i += 1;
        }
    }
    if depth == 0 {
        Ok(())
    } else {
        Err(line)
    }
}

/// #69: `-x-` puts both `/-` and `-/` into the path.
const HOSTILE: &str = "/tmp/-x-/work-/vault.so";

#[test]
fn header_survives_comment_tokens_in_so_path() {
    let so = std::path::Path::new(HOSTILE);
    for is_v3 in [false, true] {
        let intro = render::module_intro(so, "", "vault", "Vault", is_v3, None);
        check_block_comments(&intro)
            .unwrap_or_else(|l| panic!("is_v3={is_v3}: unbalanced comment at line {l}"));
        assert!(intro.starts_with(&format!("-- Generated by `qedlift` from `{HOSTILE}`.\n")));
    }
}

#[test]
fn provenance_line_escapes_newlines() {
    let line = render::generated_from_line(std::path::Path::new("/tmp/a\nb/-x-/v.so"));
    assert_eq!(
        line,
        "-- Generated by `qedlift` from `/tmp/a\\nb/-x-/v.so`.\n"
    );
}

/// End to end: a real lift from a `-x-` directory emits a module whose
/// block comments all balance (the lift itself was never the problem).
#[test]
fn lift_from_hostile_directory_emits_balanced_comments() {
    let dir = std::env::temp_dir().join(format!("qedlift-69-{}/-x-", std::process::id()));
    std::fs::create_dir_all(&dir).expect("mkdir");
    let so = dir.join("vault.so");
    std::fs::copy("../tests/fixtures/vault.so", &so).expect("copy vault.so");
    let ctx = load_binary(&so).expect("load vault.so");
    let analysis = Analysis::from_executable(&ctx.executable).expect("analyse vault.so");
    let result = lift_one(
        &so,
        &ctx,
        &analysis,
        None,
        Some("Vault".to_string()),
        None,
        None,
        None,
        None,
    )
    .expect("lift vault.so");
    let _ = std::fs::remove_dir_all(dir.parent().unwrap());
    check_block_comments(&result.lean).unwrap_or_else(|l| panic!("unbalanced comment at line {l}"));
    assert!(result.lean.contains("/-x-/vault.so"));
}
