/-
  Recovered metadata for the `transfer` instruction in `p_token.so`.
  Generated by qedrecover — do not edit by hand.

  Sources:
    .so:     tests/fixtures/p_token.so
    overlay: tests/fixtures/p_token.qedoverlay.toml
    idl:     spl_token.codama.json

  Happy/sad-path tagging is NOT yet applied — that requires a
  mollusk execution trace (M3c-full, separate workstream). Until
  then, `reachableBlocks` lists every block reachable from the
  arm entry within its enclosing function — both happy and sad.
-/

namespace QedRecover.Transfer

/-- The MIR intrinsic this instruction claims to refine. -/
def refinesIntrinsic : String := "Mir.tokenTransfer"

/-- CU budget claimed by the overlay. -/
def cuBudget : Nat := 76

/-- Account roles, in instruction-account order (from IDL). -/
def accountRoles : List String :=
  [
    "source",
    "destination",
    "authority"
  ]

/-- Discriminator value selecting this instruction. -/
def discriminatorValue : Nat := 3
/-- Discriminator width in bytes (from IDL number type). -/
def discriminatorWidth : Nat := 1

/-- Recovered dispatcher site in solana-sbpf analysis-PC space.
    Note: this is an *insn-slot* index — `lddw` is 16 bytes but
    1 slot, so analysis PC ≠ byte offset / 8. -/
def dispatchLoadPc : Nat := 198
def dispatchJeqPc  : Nat := 199
def armEntryPc     : Nat := 309

/-- Reachable basic blocks from the arm entry, bounded to the
    enclosing function. Entries are `(startPc, endPc, destinations)`
    where `endPc` is exclusive and destinations are block-start PCs. -/
def reachableBlocks : List (Nat × Nat × List Nat) :=
  [
    (282, 285, [312, 5204]),
    (285, 288, [315, 5204]),
    (4839, 4842, [5207, 5078]),
    (288, 289, [316, 5869]),
    (4842, 4845, [5210, 5078]),
    (4725, 4728, [5081]),
    (289, 292, [320, 5857]),
    (5437, 5439, [5871, 6159]),
    (4845, 4848, [5213, 5078]),
    (4728, 4731, [3797]),
    (292, 294, [323, 5869]),
    (5428, 5431, [5861, 5869]),
    (5439, 5442, [5874, 5078]),
    (5716, 5717, [6160]),
    (4848, 4851, [5216, 5078]),
    (3541, 3542, [3798]),
    (294, 297, [327, 5869]),
    (5431, 5434, [5865, 5869]),
    (5442, 5446, [5878, 5879]),
    (5717, 5718, [5078]),
    (4851, 4852, [5217, 5443]),
    (3542, 3543, []),
    (297, 300, [331, 5869]),
    (5434, 5437, [5869, 6898]),
    (5446, 5447, [5879]),
    (5447, 5448, [5880, 5446]),
    (4852, 4855, [5221, 5431]),
    (5052, 5054, [5445, 6159]),
    (300, 303, [335, 5869]),
    (6429, 6431, [6900, 6903]),
    (5448, 5452, [5885, 6160]),
    (5055, 5064, [5455, 3798]),
    (4855, 4857, [5224, 5443]),
    (5043, 5046, [5435, 5443]),
    (5054, 5055, [5446, 5880]),
    (303, 304, [6898]),
    (6431, 6433, [6902, 5871]),
    (6434, 6436, [6905, 5471]),
    (5452, 5455, [5889, 6160]),
    (5064, 5071, [3798]),
    (4857, 4860, [5228, 5443]),
    (5046, 5049, [5439, 5443]),
    (6433, 6434, [6159]),
    (6436, 6438, [5078]),
    (5080, 5082, [5078]),
    (5455, 5458, [5893, 6160]),
    (4860, 4863, [5232, 5443]),
    (5049, 5052, [5443, 6445]),
    (5458, 5461, [5897, 6160]),
    (4863, 4866, [5236, 5443]),
    (5992, 5994, [6447, 6903]),
    (5461, 5464, [5901, 6160]),
    (4866, 4867, [6445]),
    (5994, 5996, [6449, 5445]),
    (5464, 5467, [5905, 6160]),
    (5996, 5997, [6159]),
    (5467, 5470, [5909, 6160]),
    (5470, 5474, [5914, 3798]),
    (5474, 5475, [6160])
  ]

/-- Sanity-check totals. -/
def blockCount        : Nat := 59
def totalInstructions : Nat := 151

end QedRecover.Transfer
