//! Emitters for the recovered arm metadata: the `.recovered.lean` module and the
//! qedmeta `.toml` sidecar (issue #37/#41 producer half).

use std::collections::BTreeSet;

use solana_sbpf::static_analysis::CfgNode;

use qed_analysis::{
    layout::{AccountLayout, FieldKind},
    PcMap,
};

use crate::args::Args;
use crate::recover::{Idl, IdlInstruction, Overlay, OverlayIx, RecoveredArm};

/// Everything both emitters need about one recovered instruction: the overlay + IDL
/// context, the recovery result, and the optional happy-path trace.
pub(crate) struct EmitCtx<'a> {
    pub(crate) overlay: &'a Overlay,
    pub(crate) ovix: &'a OverlayIx,
    pub(crate) idl_ix: &'a IdlInstruction,
    pub(crate) recovered: &'a RecoveredArm<'a>,
    pub(crate) trace: Option<&'a BTreeSet<usize>>,
}

/// Cheap PascalCase conversion for Lean namespace names.
fn pascal(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut up = true;
    for c in s.chars() {
        if c == '_' || c == '-' {
            up = true;
            continue;
        }
        if up {
            out.extend(c.to_uppercase());
            up = false;
        } else {
            out.push(c);
        }
    }
    out
}

fn field_kind_name(kind: &FieldKind) -> &'static str {
    match kind {
        FieldKind::Pubkey => "pubkey",
        FieldKind::U64 => "u64",
        FieldKind::Byte => "byte",
        FieldKind::Bytes(_) => "bytes",
    }
}

/// Emit the recovered arm metadata as a Lean module.
pub(crate) fn emit_lean<W: std::io::Write>(
    out: &mut W,
    args: &Args,
    pc_map: &PcMap,
    ctx: &EmitCtx<'_>,
) -> std::io::Result<()> {
    let EmitCtx {
        overlay,
        ovix,
        idl_ix,
        recovered,
        trace,
    } = *ctx;
    let module = format!("QedRecover.{}", pascal(&ovix.name));
    let on_trace = |b: &CfgNode| -> bool {
        trace.is_some_and(|t| {
            t.range(b.instructions.start..b.instructions.end)
                .next()
                .is_some()
        })
    };

    writeln!(out, "/-")?;
    writeln!(
        out,
        "  Recovered metadata for the `{}` instruction in `{}`.",
        ovix.name,
        args.so
            .file_name()
            .map(|s| s.to_string_lossy())
            .unwrap_or_default()
    )?;
    writeln!(out, "  Generated by qedrecover — do not edit by hand.")?;
    writeln!(out)?;
    writeln!(out, "  Sources:")?;
    writeln!(out, "    .so:     {}", args.so.display())?;
    writeln!(out, "    overlay: {}", args.overlay.display())?;
    writeln!(out, "    idl:     {}", overlay.idl)?;
    writeln!(out)?;
    if trace.is_some() {
        writeln!(out, "  Happy-path tagging applied from an execution trace")?;
        writeln!(out, "  (`--trace`, captured via scripts/capture_trace.sh).")?;
        writeln!(
            out,
            "  `happyPathBlocks` lists the block-start PCs the trace"
        )?;
        writeln!(
            out,
            "  executed; the remaining `reachableBlocks` entries were not"
        )?;
        writeln!(
            out,
            "  on the traced path (error handlers and untaken branches)."
        )?;
    } else {
        writeln!(
            out,
            "  Happy/sad-path tagging NOT applied (no `--trace` given)."
        )?;
        writeln!(
            out,
            "  `reachableBlocks` lists every block reachable from the arm"
        )?;
        writeln!(
            out,
            "  entry within its enclosing function — both happy and sad."
        )?;
    }
    writeln!(out, "-/")?;
    writeln!(out)?;
    // Long literal lists (a correctly-rooted slice can be thousands of
    // blocks) blow Lean's default elaborator recursion depth.
    writeln!(out, "set_option maxRecDepth 65536")?;
    writeln!(out)?;
    writeln!(out, "namespace {}", module)?;
    writeln!(out)?;

    // `refines`/`cu_budget` are optional; emit empty/0 sentinels so the generated Lean is well-formed.
    writeln!(
        out,
        "/-- The MIR intrinsic this instruction claims to refine. -/"
    )?;
    writeln!(
        out,
        "def refinesIntrinsic : String := \"{}\"",
        ovix.refines.as_deref().unwrap_or("")
    )?;
    writeln!(out)?;
    writeln!(out, "/-- CU budget claimed by the overlay. -/")?;
    writeln!(out, "def cuBudget : Nat := {}", ovix.cu_budget.unwrap_or(0))?;
    writeln!(out)?;

    writeln!(
        out,
        "/-- Account roles, in instruction-account order (from IDL). -/"
    )?;
    writeln!(out, "def accountRoles : List String :=")?;
    writeln!(out, "  [")?;
    for (i, acc) in idl_ix.accounts.iter().enumerate() {
        let sep = if i + 1 < idl_ix.accounts.len() {
            ","
        } else {
            ""
        };
        writeln!(out, "    \"{}\"{}", acc.name, sep)?;
    }
    writeln!(out, "  ]")?;
    writeln!(out)?;

    writeln!(
        out,
        "/-- Discriminator value selecting this instruction. -/"
    )?;
    writeln!(
        out,
        "def discriminatorValue : Nat := {}",
        recovered.disc.value
    )?;
    writeln!(
        out,
        "/-- Discriminator width in bytes (from IDL number type). -/"
    )?;
    writeln!(
        out,
        "def discriminatorWidth : Nat := {}",
        recovered.disc.size
    )?;
    writeln!(out)?;

    writeln!(
        out,
        "/-- Recovered dispatcher site, in logical PC space (decoded-array"
    )?;
    writeln!(
        out,
        "    index, `lddw` = one element — matches Lean decode, qedlift,"
    )?;
    writeln!(out, "    and `.pcs` trace numbering). -/")?;
    writeln!(out, "def dispatchLoadPc : Nat := {}", recovered.load_pc)?;
    writeln!(out, "def dispatchJeqPc  : Nat := {}", recovered.jeq_pc)?;
    writeln!(
        out,
        "def armEntryPc     : Nat := {}",
        recovered.arm_entry_logical
    )?;
    writeln!(out)?;

    // Destinations are slot-space cfg keys; convert to logical. Unresolvable keys emitted as-is.
    writeln!(
        out,
        "/-- Reachable basic blocks from the arm entry, bounded to the"
    )?;
    writeln!(
        out,
        "    enclosing function. Entries are `(startPc, endPc, destinations)`"
    )?;
    writeln!(
        out,
        "    where `endPc` is exclusive and destinations are block-start PCs."
    )?;
    writeln!(
        out,
        "    All PCs logical (same space as the other defs here). -/"
    )?;
    writeln!(out, "def reachableBlocks : List (Nat × Nat × List Nat) :=")?;
    writeln!(out, "  [")?;
    for (i, b) in recovered.arm_blocks.iter().enumerate() {
        let dests = b
            .destinations
            .iter()
            .map(|&d| pc_map.slot_to_logical(d).unwrap_or(d).to_string())
            .collect::<Vec<_>>()
            .join(", ");
        let sep = if i + 1 < recovered.arm_blocks.len() {
            ","
        } else {
            ""
        };
        writeln!(
            out,
            "    ({}, {}, [{}]){}",
            b.instructions.start, b.instructions.end, dests, sep
        )?;
    }
    writeln!(out, "  ]")?;
    writeln!(out)?;

    writeln!(
        out,
        "/-- Blocks that exit with a CONSTANT r0 (directly, or via a jump /"
    )?;
    writeln!(out, "    fall-through to a shared bare-`exit` block), as")?;
    writeln!(
        out,
        "    `(blockStartPc, exitCode)`. Code 0 entries are the success"
    )?;
    writeln!(
        out,
        "    funnels; nonzero entries are constant error landings. Each is"
    )?;
    writeln!(
        out,
        "    discharged in one `apply` of `errorExit{{,Ja}}{{,_lddw}}_spec`"
    )?;
    writeln!(out, "    (InstructionSpecs/Terminating.lean). -/")?;
    writeln!(out, "def constExitBlocks : List (Nat × Nat) :=")?;
    writeln!(
        out,
        "  [{}]",
        recovered
            .const_exits
            .iter()
            .map(|exit| format!("({}, {})", exit.block_start, exit.exit_code))
            .collect::<Vec<_>>()
            .join(", ")
    )?;
    writeln!(out)?;

    writeln!(
        out,
        "/-- Recognised instruction idioms, as `(pc, tag)` — the asm-side"
    )?;
    writeln!(
        out,
        "    domain vocabulary. `u64_field_{{increment,decrement}}` is the"
    )?;
    writeln!(
        out,
        "    balance-mutation triple; `error_propagation_check` marks a"
    )?;
    writeln!(
        out,
        "    call whose r0 result is branch-tested (the compiled `Err(e)`"
    )?;
    writeln!(
        out,
        "    propagation seam); `read_discriminator` is the dispatch load. -/"
    )?;
    writeln!(out, "def idioms : List (Nat × String) :=")?;
    writeln!(out, "  [")?;
    for (i, idm) in recovered.idiom_tags.iter().enumerate() {
        let sep = if i + 1 < recovered.idiom_tags.len() {
            ","
        } else {
            ""
        };
        writeln!(
            out,
            "    ({}, \"{} {}\"){}",
            idm.pc, idm.name, idm.detail, sep
        )?;
    }
    writeln!(out, "  ]")?;
    writeln!(out)?;

    if let Some(t) = trace {
        let happy: Vec<usize> = recovered
            .arm_blocks
            .iter()
            .filter(|b| on_trace(b))
            .map(|b| b.instructions.start)
            .collect();
        writeln!(
            out,
            "/-- Block-start PCs the execution trace passed through — the"
        )?;
        writeln!(
            out,
            "    happy path of this instruction, in block order. Blocks in"
        )?;
        writeln!(
            out,
            "    `reachableBlocks` but not here were never executed by the"
        )?;
        writeln!(out, "    trace (error handlers / untaken branches). -/")?;
        writeln!(out, "def happyPathBlocks : List Nat :=")?;
        writeln!(
            out,
            "  [{}]",
            happy
                .iter()
                .map(|p| p.to_string())
                .collect::<Vec<_>>()
                .join(", ")
        )?;
        writeln!(out)?;
        writeln!(out, "/-- Number of PCs in the source trace. -/")?;
        writeln!(out, "def tracePcCount : Nat := {}", t.len())?;
        writeln!(out)?;
    }

    writeln!(out, "/-- Sanity-check totals. -/")?;
    writeln!(
        out,
        "def blockCount        : Nat := {}",
        recovered.arm_blocks.len()
    )?;
    writeln!(
        out,
        "def totalInstructions : Nat := {}",
        recovered.arm_insns
    )?;
    writeln!(out)?;

    writeln!(out, "end {}", module)?;

    Ok(())
}

/// Emit the qedmeta `.toml` sidecar (issue #37/#41 producer half). Schema v2: populates
/// `[instruction.recovered]`, `[[instruction.idiom]]`, `[[instruction.const_exit]]`, and
/// `[[instruction.tag]]`. Does NOT emit `[instruction.proofs]` — that links a Lean theorem
/// that only the human/qedgen author can assert. All PCs are logical (decoded-array indices).
pub(crate) fn emit_qedmeta<W: std::io::Write>(
    out: &mut W,
    idl: &Idl,
    account_layouts: &[AccountLayout],
    so_sha256: &str,
    idl_sha256: &str,
    ctx: &EmitCtx<'_>,
) -> std::io::Result<()> {
    let EmitCtx {
        overlay,
        ovix,
        idl_ix,
        recovered,
        trace,
    } = *ctx;
    writeln!(
        out,
        "# qedmeta sidecar — emitted by qedrecover (do not edit by hand)."
    )?;
    writeln!(out, "# Schema: see qedsvm-rs/spec/qedmeta.md.")?;
    writeln!(out)?;
    writeln!(out, "schema_version = 2")?;
    writeln!(out, "spec_version   = \"qedmeta/0.2\"")?;
    writeln!(out)?;

    writeln!(out, "[target]")?;
    writeln!(out, "sha256       = \"{}\"", so_sha256)?;
    writeln!(out, "program_name = \"{}\"", idl.program.name)?;
    writeln!(out, "program_id   = \"{}\"", idl.program.public_key)?;
    writeln!(out)?;

    writeln!(out, "[idl]")?;
    writeln!(out, "format = \"codama\"")?;
    writeln!(out, "inline = false")?;
    writeln!(out, "ref    = \"{}\"", overlay.idl)?;
    writeln!(out, "sha256 = \"{}\"", idl_sha256)?;
    writeln!(out)?;

    for layout in account_layouts {
        writeln!(out, "[[account_layout]]")?;
        writeln!(out, "name   = \"{}\"", layout.name)?;
        writeln!(out, "source = \"codama\"")?;
        writeln!(out, "size   = {}", layout.size)?;
        writeln!(out)?;
        for field in &layout.fields {
            writeln!(out, "[[account_layout.field]]")?;
            writeln!(out, "name        = \"{}\"", field.name)?;
            writeln!(out, "offset      = {}", field.offset)?;
            writeln!(out, "kind        = \"{}\"", field_kind_name(&field.kind))?;
            if let FieldKind::Bytes(n) = &field.kind {
                writeln!(out, "width_bytes = {}", n)?;
            }
        }
        writeln!(out)?;
    }

    writeln!(out, "[[instruction]]")?;
    writeln!(out, "name      = \"{}\"", idl_ix.name)?;
    if let Some(r) = ovix.refines.as_ref() {
        writeln!(out, "refines   = \"{}\"", r)?;
    }
    if let Some(cu) = ovix.cu_budget {
        writeln!(out, "cu_budget = {}", cu)?;
    }
    writeln!(out)?;

    writeln!(out, "[instruction.discriminator]")?;
    writeln!(out, "value       = {}", recovered.disc.value)?;
    writeln!(out, "width_bytes = {}", recovered.disc.size)?;
    writeln!(out, "format      = \"{}\"", recovered.disc.format)?;
    writeln!(out)?;

    for acc in &idl_ix.accounts {
        writeln!(out, "[[instruction.account]]")?;
        writeln!(out, "name     = \"{}\"", acc.name)?;
        writeln!(out, "writable = {}", acc.is_writable)?;
        match &acc.is_signer {
            serde_json::Value::Bool(b) => writeln!(out, "signer   = {}", b)?,
            serde_json::Value::String(s) => writeln!(out, "signer   = \"{}\"", s)?,
            _ => writeln!(out, "signer   = false")?,
        }
        if let Some(layout) = ovix.account_layouts.get(&acc.name) {
            writeln!(out, "layout   = \"{}\"", layout)?;
        }
    }
    writeln!(out)?;

    // recovered facts — the section qedlift consumes
    writeln!(out, "[instruction.recovered]")?;
    writeln!(out, "dispatch_load_pc   = {}", recovered.load_pc)?;
    writeln!(out, "dispatch_jeq_pc    = {}", recovered.jeq_pc)?;
    writeln!(out, "arm_entry_pc       = {}", recovered.arm_entry_logical)?;
    writeln!(
        out,
        "enclosing_func_pc  = {}",
        recovered.enclosing_func_logical
    )?;
    writeln!(out, "block_count        = {}", recovered.arm_blocks.len())?;
    writeln!(out, "total_instructions = {}", recovered.arm_insns)?;
    // Full slice elided (1940 rows on p_token); qedlift consumes `arm_entry_pc` not the slice.
    // The `.recovered.lean` (--output) carries `reachableBlocks` for inspection.
    writeln!(out, "blocks = []")?;
    writeln!(out)?;

    for idm in &recovered.idiom_tags {
        writeln!(out, "[[instruction.idiom]]")?;
        writeln!(out, "pc      = {}", idm.pc)?;
        writeln!(out, "pattern = \"{}\"", idm.name)?;
        writeln!(out, "detail  = \"{}\"", idm.detail)?;
    }
    if !recovered.idiom_tags.is_empty() {
        writeln!(out)?;
    }

    for exit in &recovered.const_exits {
        writeln!(out, "[[instruction.const_exit]]")?;
        writeln!(out, "block_start = {}", exit.block_start)?;
        writeln!(out, "exit_code   = {}", exit.exit_code)?;
        writeln!(
            out,
            "role        = \"{}\"",
            if exit.exit_code == 0 {
                "success"
            } else {
                "error"
            }
        )?;
    }

    if let Some(t) = trace {
        for b in &recovered.arm_blocks {
            if t.range(b.instructions.start..b.instructions.end)
                .next()
                .is_some()
            {
                writeln!(out, "[[instruction.tag]]")?;
                writeln!(out, "block_start = {}", b.instructions.start)?;
                writeln!(out, "role        = \"happy\"")?;
            }
        }
    }

    Ok(())
}
