#!/usr/bin/env python3
# Codegen prototype: emit the TransferChecked refinement wiring from the lift's
# atoms. Same recipe as gen_transfer_refinement.py (now with the fixed
# codec-fold + per-atom-bridge sl_exact path), but for the TransferChecked arm:
# src account at base 96, dst account at base 21024, plus a decimals-mint
# account (addr0..addr3, wrapAdd-abstracted) framed as setup atoms.

SRC = 96       # src account base offset (debit cell at +160 = +64 of base 96)
DST = 21024    # dst account base offset (credit cell at +21088 = +64 of 21024)

# (kind, ...) — 'r<n>' for reg: (reg, value); 'm' for mem: (m, base, off, width, val).
# Transcribed from PTokenTransferChecked_balance_correct pre (the clean Nat -/+
# corollary form), lines 662-714 of the generated lift.
pre = [
 ('r1','baseAddr'), ('m','baseAddr',0,'B','oldMemB_0'), ('r2','vR2Old'),
 ('m','baseAddr',88,'D','oldMemD_1'), ('m','baseAddr',10512,'B','oldMemB_2'),
 ('m','baseAddr',10592,'D','oldMemD_3'), ('m','baseAddr',20936,'B','oldMemB_4'),
 ('m','baseAddr',21016,'D','oldMemD_5'), ('m','baseAddr',31440,'B','oldMemB_6'),
 ('m','baseAddr',31520,'D','oldMemD_7'), ('r4','vR4Old'), ('r5','vR5Old'),
 ('m','addr0',0,'D','oldMemD_8'), ('m','addr1',0,'B','oldMemB_9'),
 ('r6','vR6Old'), ('r7','vR7Old'), ('m','baseAddr',204,'B','oldMemB_10'),
 ('m','baseAddr',21132,'B','oldMemB_11'), ('r3','vR3Old'),
 ('m','addr2',0,'D','oldMemD_12'), ('m','baseAddr',160,'D','oldMemD_13'),
 ('m','baseAddr',96,'D','oldMemD_14'), ('r0','vR0Old'),
 ('m','baseAddr',21024,'D','oldMemD_15'), ('m','baseAddr',104,'D','oldMemD_16'),
 ('r8','vR8Old'), ('m','baseAddr',21032,'D','oldMemD_17'), ('r10','vR10Old'),
 ('m','vR10Old',-2080,'D','oldMemD_18'), ('m','baseAddr',112,'D','oldMemD_19'),
 ('m','baseAddr',21040,'D','oldMemD_20'), ('r9','vR9Old'),
 ('m','baseAddr',120,'D','oldMemD_21'), ('m','baseAddr',21048,'D','oldMemD_22'),
 ('m','baseAddr',10520,'D','oldMemD_23'), ('m','baseAddr',10528,'D','oldMemD_24'),
 ('m','baseAddr',10536,'D','oldMemD_25'), ('m','baseAddr',10544,'D','oldMemD_26'),
 ('m','baseAddr',10645,'B','oldMemB_27'), ('m','addr3',0,'B','oldMemB_28'),
 ('m','baseAddr',10644,'B','oldMemB_29'), ('m','baseAddr',31448,'D','oldMemD_30'),
 ('m','baseAddr',168,'B','oldMemB_31'), ('m','baseAddr',128,'D','oldMemD_32'),
 ('m','baseAddr',31456,'D','oldMemD_33'), ('m','baseAddr',136,'D','oldMemD_34'),
 ('m','baseAddr',31464,'D','oldMemD_35'), ('m','baseAddr',144,'D','oldMemD_36'),
 ('m','baseAddr',31472,'D','oldMemD_37'), ('m','baseAddr',152,'D','oldMemD_38'),
 ('m','baseAddr',31441,'B','oldMemB_39'), ('m','baseAddr',21088,'D','oldMemD_40'),
 ('m','baseAddr',205,'B','oldMemB_41'),
]
# post: register/value changes; balance cells clean (Nat -/+). Everything else flows through.
post_reg = {'r2':'oldMemD_12','r4':'oldMemD_7','r5':'oldMemD_38','r6':'toU64 0',
            'r7':'toU64 4','r3':'oldMemB_41 % 256','r0':'toU64 0','r8':'oldMemD_16',
            'r9':'oldMemD_21'}
post_mem = {
 ('baseAddr',160):'oldMemD_13 - oldMemD_12', ('baseAddr',21088):'oldMemD_40 + oldMemD_12',
 ('vR10Old',-2080):'oldMemD_13'}

def lean_off(off):
    return f"({off})" if off < 0 else f"{off}"

def atom(a, post=False):
    if a[0][0] == 'r' and a[0] != 'm':
        v = post_reg.get(a[0], a[1]) if post else a[1]
        return f"(.{a[0]} ↦ᵣ {v})"
    _, base, off, w, val = a
    if post: val = post_mem.get((base,off), val)
    arrow = '↦ₘ' if w == 'B' else '↦U64'
    return f"(effectiveAddr {base} {lean_off(off)} {arrow} {val})"

def chain(atoms, post=False):
    return " **\n      ".join(atom(a, post) for a in atoms)

def classify(a):
    if a[0][0] == 'r' and a[0] != 'm': return 'other'
    _, base, off, w, val = a
    if base == 'baseAddr' and SRC <= off < SRC + 165: return 'src'
    if base == 'baseAddr' and DST <= off < DST + 165: return 'dst'
    return 'other'

others = [a for a in pre if classify(a) == 'other']
print("setupPre count:", len(others))

nat_vars = ("baseAddr oldMemB_0 vR2Old oldMemD_1 oldMemB_2 oldMemD_3 oldMemB_4 oldMemD_5 "
 "oldMemB_6 oldMemD_7 vR4Old vR5Old oldMemD_8 oldMemB_9 vR6Old vR7Old oldMemB_10 oldMemB_11 "
 "vR3Old oldMemD_12 oldMemD_13 oldMemD_14 vR0Old oldMemD_15 oldMemD_16 vR8Old oldMemD_17 "
 "vR10Old oldMemD_18 oldMemD_19 oldMemD_20 vR9Old oldMemD_21 oldMemD_22 oldMemD_23 oldMemD_24 "
 "oldMemD_25 oldMemD_26 oldMemB_27 oldMemB_28 oldMemB_29 oldMemD_30 oldMemB_31 oldMemD_32 "
 "oldMemD_33 oldMemD_34 oldMemD_35 oldMemD_36 oldMemD_37 oldMemD_38 oldMemB_39 oldMemD_40 "
 "oldMemB_41 addr0 addr1 addr2 addr3")

liftPre = chain(pre, False)
liftPost = chain(pre, True)
setupPre = chain(others, False)
setupPost = chain(others, True)

out = f"""\
/-
  TransferChecked asm-refines-intrinsic theorem — the SECOND real-bytecode
  refinement (after Transfer). Generated by `gen_transferchecked_refinement.py`.
  Reuses `AsmRefinesTokenTransfer` (TransferChecked has the same src-debit /
  dst-credit token effect) + the parametric `src_account_eq` / `dst_account_eq`
  aggregation lemmas — here at src base 96 and dst base 21024. The decimals-mint
  account (`addr0..addr3`, wrapAdd-abstracted) and the stack/validation cells are
  carried as opaque setup atoms.

  Same scoping note as TransferRefinement: imports `Abstract.Refinement` for
  `AsmRefinesTokenTransfer` but does NOT `open SVM.Solana.Abstract` (Abstract's
  `**` is scoped; a second overload would blow up elaboration). The
  `simp only [Nat.add_assoc, Nat.reduceAdd]` before `sl_exact` folds the codec's
  nested account-base offsets to single literals, keeping every residual defeq
  cheap (see the SL.lean `buildDefeqBridge` / `buildRightFoldIff` fixes).
-/

import SVM.SBPF.Tactic.SL
import SVM.Solana.Abstract.Refinement
import Generated.PTokenTransferCheckedTracedLifted
import PToken.TransferAggregation

namespace Examples.PTokenTransferCheckedRefinement
open SVM SVM.SBPF SVM.SBPF.Memory
open Examples.PTokenTransferAggregation

-- Generic wiring: the TransferChecked lift refines the tokenTransfer intrinsic's
-- asm obligation. cr/rr/lift abstract; the balance-correct (clean Nat -/+) form
-- is taken as the `lift` hypothesis.
set_option maxHeartbeats 800000 in
theorem refines_asm
    (cr : CodeReq) (rr : Memory.RegionTable → Prop)
    ({nat_vars} : Nat)
    (o0 o1 o2 o3 : Nat) (g1 g2 g3 g4 : ByteArray)
    (hg1 : g1.size = 35) (hg3 : g3.size = 36)
    (h72 : oldMemB_31 < 256) (h108s : oldMemB_10 < 256)
    (h109s : oldMemB_41 < 256) (h108d : oldMemB_11 < 256)
    (lift : cuTripleWithinMem 104 0 198 3542 cr
      ({liftPre})
      ({liftPost}) rr) :
    SVM.Solana.Abstract.AsmRefinesTokenTransfer cr 104 0 198 3542 rr (baseAddr + 96) (baseAddr + 21024)
      {{ mint := ⟨oldMemD_14, oldMemD_16, oldMemD_19, oldMemD_21⟩,
        owner := ⟨oldMemD_32, oldMemD_34, oldMemD_36, oldMemD_38⟩, amount := oldMemD_13,
        rest := PartialState.byteBA oldMemB_31 ++ (g1 ++
          (PartialState.byteBA oldMemB_10 ++ (PartialState.byteBA oldMemB_41 ++ g2))) }}
      {{ mint := ⟨oldMemD_15, oldMemD_17, oldMemD_20, oldMemD_22⟩,
        owner := ⟨o0, o1, o2, o3⟩, amount := oldMemD_40,
        rest := g3 ++ (PartialState.byteBA oldMemB_11 ++ g4) }}
      oldMemD_12
      ({setupPre})
      ({setupPost}) := by
  unfold SVM.Solana.Abstract.AsmRefinesTokenTransfer
  simp only [SVM.Solana.Abstract.TokenAccount.withAmount]
  rw [src_account_eq (baseAddr + 96) oldMemD_14 oldMemD_16 oldMemD_19 oldMemD_21
        oldMemD_32 oldMemD_34 oldMemD_36 oldMemD_38 oldMemD_13 oldMemB_31 oldMemB_10 oldMemB_41
        g1 g2 hg1 h72 h108s h109s,
      dst_account_eq (baseAddr + 21024) oldMemD_15 oldMemD_17 oldMemD_20 oldMemD_22
        o0 o1 o2 o3 oldMemD_40 oldMemB_11 g3 g4 hg3 h108d,
      src_account_eq (baseAddr + 96) oldMemD_14 oldMemD_16 oldMemD_19 oldMemD_21
        oldMemD_32 oldMemD_34 oldMemD_36 oldMemD_38 (oldMemD_13 - oldMemD_12) oldMemB_31 oldMemB_10 oldMemB_41
        g1 g2 hg1 h72 h108s h109s,
      dst_account_eq (baseAddr + 21024) oldMemD_15 oldMemD_17 oldMemD_20 oldMemD_22
        o0 o1 o2 o3 (oldMemD_40 + oldMemD_12) oldMemB_11 g3 g4 hg3 h108d]
  simp only [pubkeyIs]
  have framed := cuTripleWithinMem_frame_right
    ( (effectiveAddr baseAddr 21056 ↦U64 o0) ** (effectiveAddr baseAddr 21064 ↦U64 o1) **
      (effectiveAddr baseAddr 21072 ↦U64 o2) ** (effectiveAddr baseAddr 21080 ↦U64 o3) **
      memBytesIs (baseAddr + 169) g1 ** memBytesIs (baseAddr + 206) g2 **
      memBytesIs (baseAddr + 21096) g3 ** memBytesIs (baseAddr + 21133) g4 )
    (by sl_pcfree) lift
  simp only [Nat.add_assoc, Nat.reduceAdd]
  sl_exact framed

end Examples.PTokenTransferCheckedRefinement
"""
open('/Users/abishek/code/qedsvm/examples/lean/PToken/TransferCheckedRefinement.lean','w').write(out)
print("wrote TransferCheckedRefinement.lean")
