/-
  WIP — NOT registered in the lakefile (so `lake build` skips it). Generated by
  `gen_transfer_refinement.py` (the codegen prototype for what qedlift will emit
  per-arm). Wires the real trace-guided Transfer lift to `AsmRefinesTokenTransfer`
  (the tokenTransfer intrinsic) via the SL bridges + `src_account_eq`/
  `dst_account_eq` + `cuTripleWithinMem_frame_right` + `sl_exact`.

  STATUS (2026-05-31): the previous commit's stated blocker — "`sl_exact`'s
  `buildPermuteIff` is an O(n²) defeq perf wall" — was a MISDIAGNOSIS. `sl_exact`
  is never even reached. The real wall was statement *elaboration*: both `**`
  notations (`SVM.SBPF.sepConj` and `SVM.Solana.Abstract.sepConj`) were declared
  with global `infixr`, so merely importing `SVM.Solana.Abstract.Refinement` put
  a second `**` overload into scope and overload resolution over the ~48-atom
  nested chains blew up (>13 min on import alone). Fixed by making Abstract's
  `**` `scoped` (see `SVM/Solana/Abstract/SepLogic.lean`) AND not `open`ing
  Abstract here — the few Abstract names are fully qualified. The statement now
  elaborates in ~1.5s and `sl_exact` is reached in ~14s.

  REMAINING BLOCKER (genuine, now visible): `sl_exact framed` fails with an
  application type mismatch — `framed`'s post (liftPost ** codec-frame) is NOT a
  permutation of the goal's post after the `src_account_eq`/`dst_account_eq`
  aggregation rewrites. This is the fine→coarse SL field-aggregation alignment,
  i.e. the codec-wrap gating noted in the qedlift status. Not a perf problem.
-/

import SVM.SBPF.Tactic.SL
import SVM.Solana.Abstract.Refinement
import Generated.PTokenTransferTracedLifted
import PToken.TransferAggregation

namespace Examples.PTokenTransferRefinement
open SVM SVM.SBPF SVM.SBPF.Memory
open Examples.PTokenTransferAggregation

-- Generic wiring: any lift with the transfer happy-path shape refines
-- the tokenTransfer intrinsic's asm obligation. cr/rr/lift abstract.
set_option maxHeartbeats 800000 in
theorem refines_asm
    (cr : CodeReq) (rr : Memory.RegionTable → Prop)
    (baseAddr addr0 oldMemB_0 vR2Old oldMemD_1 oldMemB_2 oldMemD_3 oldMemB_4 oldMemD_5 vR4Old vR3Old oldMemD_6 oldMemB_7 vR6Old vR7Old oldMemB_8 oldMemB_9 vR5Old oldMemD_10 oldMemD_11 oldMemD_12 oldMemD_13 vR0Old oldMemD_14 oldMemD_15 oldMemD_16 oldMemD_17 oldMemD_18 oldMemD_19 oldMemD_20 oldMemB_21 oldMemD_22 oldMemD_23 oldMemD_24 oldMemD_25 oldMemD_26 oldMemD_27 oldMemD_28 oldMemB_29 oldMemD_30 oldMemB_31 : Nat)
    (o0 o1 o2 o3 : Nat) (g1 g2 g3 g4 : ByteArray)
    (hg1 : g1.size = 35) (hg3 : g3.size = 36)
    (h72 : oldMemB_21 < 256) (h108s : oldMemB_8 < 256)
    (h109s : oldMemB_31 < 256) (h108d : oldMemB_9 < 256)
    (lift : cuTripleWithinMem 75 0 198 3542 cr
      ((.r1 ↦ᵣ baseAddr) **
      (effectiveAddr baseAddr 0 ↦ₘ oldMemB_0) **
      (.r2 ↦ᵣ vR2Old) **
      (effectiveAddr baseAddr 88 ↦U64 oldMemD_1) **
      (effectiveAddr baseAddr 10512 ↦ₘ oldMemB_2) **
      (effectiveAddr baseAddr 10592 ↦U64 oldMemD_3) **
      (effectiveAddr baseAddr 21016 ↦ₘ oldMemB_4) **
      (effectiveAddr baseAddr 21096 ↦U64 oldMemD_5) **
      (.r4 ↦ᵣ vR4Old) **
      (.r3 ↦ᵣ vR3Old) **
      (effectiveAddr addr0 31352 ↦U64 oldMemD_6) **
      (effectiveAddr addr0 31360 ↦ₘ oldMemB_7) **
      (.r6 ↦ᵣ vR6Old) **
      (.r7 ↦ᵣ vR7Old) **
      (effectiveAddr baseAddr 204 ↦ₘ oldMemB_8) **
      (effectiveAddr baseAddr 10708 ↦ₘ oldMemB_9) **
      (.r5 ↦ᵣ vR5Old) **
      (effectiveAddr addr0 31361 ↦U64 oldMemD_10) **
      (effectiveAddr baseAddr 160 ↦U64 oldMemD_11) **
      (effectiveAddr baseAddr 10600 ↦U64 oldMemD_12) **
      (effectiveAddr baseAddr 96 ↦U64 oldMemD_13) **
      (.r0 ↦ᵣ vR0Old) **
      (effectiveAddr baseAddr 10608 ↦U64 oldMemD_14) **
      (effectiveAddr baseAddr 104 ↦U64 oldMemD_15) **
      (effectiveAddr baseAddr 10616 ↦U64 oldMemD_16) **
      (effectiveAddr baseAddr 112 ↦U64 oldMemD_17) **
      (effectiveAddr baseAddr 10624 ↦U64 oldMemD_18) **
      (effectiveAddr baseAddr 120 ↦U64 oldMemD_19) **
      (effectiveAddr baseAddr 21024 ↦U64 oldMemD_20) **
      (effectiveAddr baseAddr 168 ↦ₘ oldMemB_21) **
      (effectiveAddr baseAddr 128 ↦U64 oldMemD_22) **
      (effectiveAddr baseAddr 21032 ↦U64 oldMemD_23) **
      (effectiveAddr baseAddr 136 ↦U64 oldMemD_24) **
      (effectiveAddr baseAddr 21040 ↦U64 oldMemD_25) **
      (effectiveAddr baseAddr 144 ↦U64 oldMemD_26) **
      (effectiveAddr baseAddr 21048 ↦U64 oldMemD_27) **
      (effectiveAddr baseAddr 152 ↦U64 oldMemD_28) **
      (effectiveAddr baseAddr 21017 ↦ₘ oldMemB_29) **
      (effectiveAddr baseAddr 10664 ↦U64 oldMemD_30) **
      (effectiveAddr baseAddr 205 ↦ₘ oldMemB_31))
      ((.r1 ↦ᵣ baseAddr) **
      (effectiveAddr baseAddr 0 ↦ₘ oldMemB_0) **
      (.r2 ↦ᵣ oldMemD_10) **
      (effectiveAddr baseAddr 88 ↦U64 oldMemD_1) **
      (effectiveAddr baseAddr 10512 ↦ₘ oldMemB_2) **
      (effectiveAddr baseAddr 10592 ↦U64 oldMemD_3) **
      (effectiveAddr baseAddr 21016 ↦ₘ oldMemB_4) **
      (effectiveAddr baseAddr 21096 ↦U64 oldMemD_5) **
      (.r4 ↦ᵣ oldMemB_29 % 256) **
      (.r3 ↦ᵣ oldMemB_31 % 256) **
      (effectiveAddr addr0 31352 ↦U64 oldMemD_6) **
      (effectiveAddr addr0 31360 ↦ₘ oldMemB_7) **
      (.r6 ↦ᵣ toU64 0) **
      (.r7 ↦ᵣ toU64 4) **
      (effectiveAddr baseAddr 204 ↦ₘ oldMemB_8) **
      (effectiveAddr baseAddr 10708 ↦ₘ oldMemB_9) **
      (.r5 ↦ᵣ oldMemD_27) **
      (effectiveAddr addr0 31361 ↦U64 oldMemD_10) **
      (effectiveAddr baseAddr 160 ↦U64 oldMemD_11 - oldMemD_10) **
      (effectiveAddr baseAddr 10600 ↦U64 oldMemD_12) **
      (effectiveAddr baseAddr 96 ↦U64 oldMemD_13) **
      (.r0 ↦ᵣ toU64 0) **
      (effectiveAddr baseAddr 10608 ↦U64 oldMemD_14) **
      (effectiveAddr baseAddr 104 ↦U64 oldMemD_15) **
      (effectiveAddr baseAddr 10616 ↦U64 oldMemD_16) **
      (effectiveAddr baseAddr 112 ↦U64 oldMemD_17) **
      (effectiveAddr baseAddr 10624 ↦U64 oldMemD_18) **
      (effectiveAddr baseAddr 120 ↦U64 oldMemD_19) **
      (effectiveAddr baseAddr 21024 ↦U64 oldMemD_20) **
      (effectiveAddr baseAddr 168 ↦ₘ oldMemB_21) **
      (effectiveAddr baseAddr 128 ↦U64 oldMemD_22) **
      (effectiveAddr baseAddr 21032 ↦U64 oldMemD_23) **
      (effectiveAddr baseAddr 136 ↦U64 oldMemD_24) **
      (effectiveAddr baseAddr 21040 ↦U64 oldMemD_25) **
      (effectiveAddr baseAddr 144 ↦U64 oldMemD_26) **
      (effectiveAddr baseAddr 21048 ↦U64 oldMemD_27) **
      (effectiveAddr baseAddr 152 ↦U64 oldMemD_28) **
      (effectiveAddr baseAddr 21017 ↦ₘ oldMemB_29) **
      (effectiveAddr baseAddr 10664 ↦U64 oldMemD_30 + oldMemD_10) **
      (effectiveAddr baseAddr 205 ↦ₘ oldMemB_31)) rr) :
    SVM.Solana.Abstract.AsmRefinesTokenTransfer cr 75 0 198 3542 rr (baseAddr + 96) (baseAddr + 10600)
      { mint := ⟨oldMemD_13, oldMemD_15, oldMemD_17, oldMemD_19⟩,
        owner := ⟨oldMemD_22, oldMemD_24, oldMemD_26, oldMemD_28⟩, amount := oldMemD_11,
        rest := PartialState.byteBA oldMemB_21 ++ (g1 ++
          (PartialState.byteBA oldMemB_8 ++ (PartialState.byteBA oldMemB_31 ++ g2))) }
      { mint := ⟨oldMemD_12, oldMemD_14, oldMemD_16, oldMemD_18⟩,
        owner := ⟨o0, o1, o2, o3⟩, amount := oldMemD_30,
        rest := g3 ++ (PartialState.byteBA oldMemB_9 ++ g4) }
      oldMemD_10
      ((.r1 ↦ᵣ baseAddr) **
      (effectiveAddr baseAddr 0 ↦ₘ oldMemB_0) **
      (.r2 ↦ᵣ vR2Old) **
      (effectiveAddr baseAddr 88 ↦U64 oldMemD_1) **
      (effectiveAddr baseAddr 10512 ↦ₘ oldMemB_2) **
      (effectiveAddr baseAddr 10592 ↦U64 oldMemD_3) **
      (effectiveAddr baseAddr 21016 ↦ₘ oldMemB_4) **
      (effectiveAddr baseAddr 21096 ↦U64 oldMemD_5) **
      (.r4 ↦ᵣ vR4Old) **
      (.r3 ↦ᵣ vR3Old) **
      (effectiveAddr addr0 31352 ↦U64 oldMemD_6) **
      (effectiveAddr addr0 31360 ↦ₘ oldMemB_7) **
      (.r6 ↦ᵣ vR6Old) **
      (.r7 ↦ᵣ vR7Old) **
      (.r5 ↦ᵣ vR5Old) **
      (effectiveAddr addr0 31361 ↦U64 oldMemD_10) **
      (.r0 ↦ᵣ vR0Old) **
      (effectiveAddr baseAddr 21024 ↦U64 oldMemD_20) **
      (effectiveAddr baseAddr 21032 ↦U64 oldMemD_23) **
      (effectiveAddr baseAddr 21040 ↦U64 oldMemD_25) **
      (effectiveAddr baseAddr 21048 ↦U64 oldMemD_27) **
      (effectiveAddr baseAddr 21017 ↦ₘ oldMemB_29))
      ((.r1 ↦ᵣ baseAddr) **
      (effectiveAddr baseAddr 0 ↦ₘ oldMemB_0) **
      (.r2 ↦ᵣ oldMemD_10) **
      (effectiveAddr baseAddr 88 ↦U64 oldMemD_1) **
      (effectiveAddr baseAddr 10512 ↦ₘ oldMemB_2) **
      (effectiveAddr baseAddr 10592 ↦U64 oldMemD_3) **
      (effectiveAddr baseAddr 21016 ↦ₘ oldMemB_4) **
      (effectiveAddr baseAddr 21096 ↦U64 oldMemD_5) **
      (.r4 ↦ᵣ oldMemB_29 % 256) **
      (.r3 ↦ᵣ oldMemB_31 % 256) **
      (effectiveAddr addr0 31352 ↦U64 oldMemD_6) **
      (effectiveAddr addr0 31360 ↦ₘ oldMemB_7) **
      (.r6 ↦ᵣ toU64 0) **
      (.r7 ↦ᵣ toU64 4) **
      (.r5 ↦ᵣ oldMemD_27) **
      (effectiveAddr addr0 31361 ↦U64 oldMemD_10) **
      (.r0 ↦ᵣ toU64 0) **
      (effectiveAddr baseAddr 21024 ↦U64 oldMemD_20) **
      (effectiveAddr baseAddr 21032 ↦U64 oldMemD_23) **
      (effectiveAddr baseAddr 21040 ↦U64 oldMemD_25) **
      (effectiveAddr baseAddr 21048 ↦U64 oldMemD_27) **
      (effectiveAddr baseAddr 21017 ↦ₘ oldMemB_29)) := by
  unfold SVM.Solana.Abstract.AsmRefinesTokenTransfer
  simp only [SVM.Solana.Abstract.TokenAccount.withAmount,
             SVM.Solana.Abstract.TokenAccount.amount]
  rw [src_account_eq (baseAddr + 96) oldMemD_13 oldMemD_15 oldMemD_17 oldMemD_19
        oldMemD_22 oldMemD_24 oldMemD_26 oldMemD_28 oldMemD_11 oldMemB_21 oldMemB_8 oldMemB_31
        g1 g2 hg1 h72 h108s h109s,
      dst_account_eq (baseAddr + 10600) oldMemD_12 oldMemD_14 oldMemD_16 oldMemD_18
        o0 o1 o2 o3 oldMemD_30 oldMemB_9 g3 g4 hg3 h108d,
      src_account_eq (baseAddr + 96) oldMemD_13 oldMemD_15 oldMemD_17 oldMemD_19
        oldMemD_22 oldMemD_24 oldMemD_26 oldMemD_28 (oldMemD_11 - oldMemD_10) oldMemB_21 oldMemB_8 oldMemB_31
        g1 g2 hg1 h72 h108s h109s,
      dst_account_eq (baseAddr + 10600) oldMemD_12 oldMemD_14 oldMemD_16 oldMemD_18
        o0 o1 o2 o3 (oldMemD_30 + oldMemD_10) oldMemB_9 g3 g4 hg3 h108d]
  simp only [pubkeyIs]
  have framed := cuTripleWithinMem_frame_right
    ( (effectiveAddr baseAddr 10632 ↦U64 o0) ** (effectiveAddr baseAddr 10640 ↦U64 o1) **
      (effectiveAddr baseAddr 10648 ↦U64 o2) ** (effectiveAddr baseAddr 10656 ↦U64 o3) **
      memBytesIs (baseAddr + 169) g1 ** memBytesIs (baseAddr + 206) g2 **
      memBytesIs (baseAddr + 10672) g3 ** memBytesIs (baseAddr + 10709) g4 )
    (by sl_pcfree) lift
  sl_exact framed

end Examples.PTokenTransferRefinement
